
ALTER TABLE table1
	ADD COLUMN IF NOT EXISTS col2 integer,
	ADD COLUMN IF NOT EXISTS col3 integer;
UPDATE  table1 SET col2=0 WHERE col2 is null;
ALTER  TABLE table1 ALTER  COLUMN col2 SET DEFAULT 0;
ALTER  TABLE table1 ALTER  COLUMN col2 SET NOT NULL;
UPDATE  table1 SET col3=5 WHERE col3 is null;
ALTER  TABLE table1 ALTER  COLUMN  col3 SET DEFAULT 5;
ALTER  TABLE table1 ALTER  COLUMN col3 SET NOT NULL;

ALTER TABLE table1
	ALTER COLUMN col2 DROP DEFAULT;